application:
  testfile: test.csv
  locale:
    language: en
    country: EN

spring:
  profiles:
    active: messages
  shell:
    interactive:
      enabled: false

logging:
  level:
    root: ERROR