application:
  testfile: test.csv
  locale:
    language: en
    country: EN

spring:
  profiles:
    active: messages, shell
  shell:
    interactive:
      enabled: false

logging:
  level:
    root: DEBUG

  shell:
    interactive:
      enabled: true